export const RouteBase = {
  Login: "/login",
  Cart: "/cart",
  Product: "/admin/product",
  Register: "/register",
  CreateProduct: "/admin/product/create",
  EditProduct: "/admin/product/edit/:id",
  Category: "/admin/category",
  CreateCategory: "/admin/category/create",
  EditCategory: "/admin/category/edit/:id",
  Size: "/admin/size",
  CreateSize: "/admin/size/create",
  EditSize: "/admin/size/edit/:id",
  Color: "/admin/color",
  CreateColor: "/admin/color/create",
  EditColor: "/admin/color/edit/:id",
  Classify: "/admin/classify",
  CreateClassify: "/admin/classify/create",
  EditClassify: "/admin/classify/edit/:id",
};
